### ISSUE TITLE
How is token auth working right now?

### ISSUE THREAD

**Issue by colemickens** [Azure/go-autorest#127]
I realize there's some irony in me having written some of this, but I'm confused how cert auth is working at all. Or at least in any scenario that requires refreshing...       

As far as I can tell, in `refreshInternal` it always sets the `grant_type` to client_credentials even if a cert is used... I'm shocked this is working for cert cases (but it is because @jkapil uses it...)

We should probably set the grant_type inside `SetAuthValues` as we do for the other fields... But still... how is this working?

cc: @jkapil @Cosmincojocar

**Comment by colemickens** [comment]
Looks like on first request, it just signs the JWT, gets back a token and all is golden. But if refreshInternal were ever called with a cert based token, I'm not sure it's going to properly get a new token with the cert.

I'm afraid I don't have time to dig into these much right now, but I wanted to get them out of my head at least for awareness.

**Comment by cosmincojocar** [comment]
@colemickens AAD returns a refresh token only for device code flow, because this flow requires user authentication and consent. In the client credentials flow there isn't any refresh token, basically the client sends its credentials every time when a new access token is requested. Either it sends an opaque secret or a JWT sign with its private key. The AAD is able to verify the signature because the public certificate of the client was provided when the application was registered. 
 
The RefreshToken is always empty for a cert based token, due to this the refreshIntenal would work if were ever called again.

**Comment by colemickens** [comment]
Great, that was the only thing that made sense but I wasn't sure. Thanks so much for explaining!
