### ISSUE TITLE
What does the 'dev' branch mean exactly?

### ISSUE THREAD

**Issue by colemickens** [Azure/go-autorest#128]
Or is it just to stage up breaking changes so they can be released together to avoid churn?

I ask, because I'm adding MSI because I need it for Kubernetes. I can't consume a non-master branch of go-autorest in Kubernetes so I need to be able to reason about when 'dev' will get merged into 'master'.

Thanks!

**Comment by marstr** [comment]
Howdy @colemickens,

You've got it right, we realized that while folks using `godep` or `glide` can lock themselves to a particular commit or tag, folks using `go get` are tied to the master branch without a good way to get off. For that reason, as you mentioned, we want to batch together breaking changes to reduce churn.

That said, you've got a good point. There should be some ability to reason about when master will get merged with dev. As opposed to what we have now which is the very informal, "the curators of the repository have some idea of what's coming next, and will silently try to make that work out."  I'll bring this up during our next team meeting, so that we can hash out a policy.

-Martin

**Comment by marstr** [comment]
Coming back around, we've decided that our policy need to be flexible enough to accommodate the needs of each repository. What we'll do is have `master` merged into `dev` at each release. Anything that should not land in the next release (i.e. breaking changes that belong in the next major version) should live in a branch other than `dev`. We'll try to make our intentions clear by using Milestones with the appropriate version number as their title and setting the date as appropriate.

**Comment by colemickens** [comment]
Will you then open, for example, tracking issues for various features? For example, the adal+msi stuff, is there a milestone that's planned for?

(I actually wouldn't mind if it didn't get merged for a few more days so that Varun and I can chat about ASAL, in case it has any impact on `go-autorest`...)

**Comment by marstr** [comment]
Yeah, I think that makes a lot of sense. I'll open an issue to track adding ASAL.
