### ISSUE TITLE
Inability to specify apiVersion

### ISSUE THREAD

**Issue by tvi** [Azure/go-autorest#277]
This code has the same problem as https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/128 .

Because `activeDirectoryAPIVersion = "1.0"` is hardcoded I cannot delete the parameter and I am getting behaviour mismatch for when some AAD code is expecting   "aud": "spn:<>" and OIDC is expecting   "aud": "<>".

What if we would modify `NewOAuthConfig` or create `NewOAuthConfigWithAPI` where you could specify api version?

**Comment by marstr** [comment]
Howdy @tvi,

Thanks for bringing this up! It points towards a sort of broader issue, which is that we don't have sufficient support for AAD v2. I believe that there are probably substantial enough differences between the two versions that we'll need to go beyond just parameterizing the particular API Version that is to be used.

Supporting v2 has been stuck in the backlog for sometime, mainly because ARM operations have never adopted AAD v2. That said, having customer voices will help us prioritize it. I'm going to close this issue for now, because there isn't anything actionable at the moment, but this is a good note for me, @joshgav, @vladbarosan, and @jhendrixMSFT to be aware of.

Cheers.

**Comment by marstr** [comment]
See #133 for further discussion.

**Comment by tvi** [comment]
Any timeline on that? We cannot use kubernetes with AAD, because of this bug / disparity between apiserver and kubectl. It was major blocker and we had to move out of AAD into competitor service because of this.

**Comment by marstr** [comment]
I'm not sure, @joshgav may have a better idea. However, the best thing you can do is to go comment on #133 and advocate for it.

**Comment by radu-matei** [comment]
While I understand the idea of having broader support for v2, I would argue that adding a method such as  `NewOAuthConfigWithAPI `, like @tvi suggested, might be enough to support some simple scenarios for acquiring a token.

Not having this means we need to maintain our fork that implements it, which is not ideal.

**Comment by joshgav** [comment]
related: https://github.com/Azure/acs-engine/issues/4189
