### ISSUE TITLE
include authorizer setup in API client constructor functions

### ISSUE THREAD

**Issue by joshgav** [Azure/go-autorest#294]
Currently the API clients returned by our `New*Client` functions require another step before they're usable - creating and attaching an authorizer. Users have requested that the constructor-like functions return a working client with authorizer attached, adding additional parameters if needed.

Here's how we do things now:

```go
c := compute.NewVirtualMachinesClient(env.SubscriptionID())
a, _ := auth.NewAuthorizerFromEnvironment()
c.Authorizer = a
```

Could we consider adding or replacing that with something like this?

```go
c, err := compute.NewVirtualMachinesClientWithAuthorizer(env.SubscriptionID(), auth.NewAuthorizerFromEnvironment())
```

Thanks!

**Comment by joshgav** [comment]
cc @anguslees

**Comment by anguslees** [comment]
(The "user" here ;)

... or something.  I'm not super convinced about the above proposal either, so feel free to push back.

Using the current `NewFooClient` API feels like I'm duplicating a lot of multi-line boilerplate everywhere, especially because I have to repeat it for every different `Foo`, and because of go's obligatory "if err != nil { return err }" after each line.  I expect simply creating a "normal" client object to be something close to a single constructor call, and hard to misuse.  The current "assign properties afterwards" API is easy to misuse (by omitting the extra assignment statements), and "vertically verbose" even for simple cases.

The [azure-sdk-for-go-samples repo](https://github.com/Azure-Samples/azure-sdk-for-go-samples) is also a good (negative) example of the same repetitious setup boilerplate.

I note the only _real_ variance in these objects is the golang type - they're even the same BaseURI in most cases.  One suggestion might be to create a "management client" once, and pass it to all the more-specifically-typed constructors.

**Comment by marstr** [comment]
Thanks for this feedback, @anguslees. We totally agree, and are planning to consolidate all initialization into the constructor the next time we release non-swagger related breaking changes.

**Comment by jhendrixMSFT** [comment]
This is something we'll be doing in track 2 but not for track 1.
