### ISSUE TITLE
azure: Request inspection missing for polling requests

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-autorest#34]
I have a request/response inspector set on the client that prints every request/response. For Azure long-running operations the inspection for the polling "requests" is missing (but their response is inspected just fine):

* Azure **request**  method="PUT" request="https://management.azure.com/subscriptions/27b750cd-ed43-42fd-9044-8d75e124ae55/resourceGroups/docker-machine/providers/Microsoft.Network/networkSecurityGroups/foo0-firewall?api-version=2015-06-15"
* Azure **response**  method="PUT" request="https://management.azure.com/subscriptions/27b750cd-ed43-42fd-9044-8d75e124ae55/resourceGroups/docker-machine/providers/Microsoft.Network/networkSecurityGroups/foo0-firewall?api-version=2015-06-15" x-ms-request-id="e992d5dd-0255-4e8b-bff8-e9aeb49b5c3d" status="201 Created"
* Azure **response**  x-ms-request-id="dc65e42f-569a-4a29-b9dd-bbcd6e17ae49" status="200 OK" method="GET" request="https://management.azure.com/subscriptions/27b750cd-ed43-42fd-9044-8d75e124ae55/providers/Microsoft.Network/locations/westus/operations/e992d5dd-0255-4e8b-bff8-e9aeb49b5c3d?api-version=2015-06-15"

so the request of the last response is missing.

**Comment by brendandixon** [comment]
@ahmetalpbalkan This should be fixed in the PR I just submitted. The problem was where I had been invoking the WithInspection (and WithAuthorization) PrependDecorators. They were called during the creation of the initial polling / async request. They *should* be called just before each use of that request (i.e., moved into Client#Do). I've moved them.

**Comment by ahmetalpbalkan** [comment]
thanks. fixed.
