### ISSUE TITLE
Consolidate default http.Client

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/go-autorest#41]
I started seeing multiple http.Client{}s around the codebase, it's not immediately clear to me how we can consolidate these.

* [`client.go`](https://github.com/Azure/go-autorest/blob/c6f4f7f3678803fbe8975c884e80affad9d31998/autorest/client.go#L142-L147)
* [`sender.go` #1](https://github.com/Azure/go-autorest/blob/c6f4f7f3678803fbe8975c884e80affad9d31998/autorest/sender.go#L32-L34)
* [`sender.go` #2](https://github.com/Azure/go-autorest/blob/c6f4f7f3678803fbe8975c884e80affad9d31998/autorest/sender.go#L55-L57)

I just had to add a custom `http.Transport` setting to 3 different places to change the behavior. 

User should be able to set a HTTP client in a single place to be used in all requests.

@brendandixon

**Comment by brendandixon** [comment]
@ahmetalpbalkan The latter two are convenience methods not used at present in our generated code. The generated code relies only on the first. That's all you need to change to override behavior.

The two instances in sender.go are analogues to methods in prepare.go and respond.go (e.g., prepare.go#CreatePreparer). While the sender methods are not used, the others are used. Removing the sender methods simply because we're not (at present) using them leads to asymmetry (which I dislike).

The package is designed as follows: Preparers, Senders, and Responders are independent "things" that useful in a variety of patterns. Client is a helper that provides common feature support using some of those basic methods. Lastly, the generated code takes an even narrower stand in how it uses these methods.

**Comment by ahmetalpbalkan** [comment]
@brendandixon so how does a user change the client used without changing go-autorest source code?

**Comment by brendandixon** [comment]
@ahmetalpbalkan The base client must be an instance of `http.Client`. `go-autorest`, as a result, thinks in terms of "senders": Objects that implement the `Sender` interface. The `Sender` interface contains just one method, that (shock!) overlaps with `http.Client` (i.e., `Do(*http.Request) (*http.Response, error)`).

The go-autorest `Client` accepts a `Sender` (see [`client.go`](https://github.com/Azure/go-autorest/blob/c6f4f7f3678803fbe8975c884e80affad9d31998/autorest/client.go#L102)). If blank, it conjures up an `http.Client` (your first reference above), otherwise it uses the provided `Sender`.

There, if you need to really override how `Do` is done, then provide a `Sender`. That's how testing works. :)

**Comment by ahmetalpbalkan** [comment]
Ah, understood. Thanks.
